PATCH_SCSI=FALSE
PATCH_IDE=TRUE
PATCH_SD=FALSE
PATCH_FULL_ACCESS=TRUE
PATCH_INFO=TRUE
PATCH_UNSUPPORTED_OSFILE=TRUE
PATCH_PRESERVE_CONTEXT=TRUE
TEST_SHIFT=FALSE
INCLUDE_FLOPPY=TRUE
KEEP_REDUNDANT=TRUE
LARGE_DISK=FALSE

include "adfs150.asm"
