PATCH_SCSI=TRUE
PATCH_IDE=FALSE
PATCH_SD=FALSE
PATCH_FULL_ACCESS=FALSE
PATCH_INFO=FALSE
PATCH_UNSUPPORTED_OSFILE=FALSE
PATCH_PRESERVE_CONTEXT=FALSE
TEST_SHIFT=FALSE
INCLUDE_FLOPPY=TRUE
KEEP_REDUNDANT=TRUE
LARGE_DISK=FALSE

include "adfs150.asm"
